---
title       : CLT - Center Limit Theorem (for means)
subtitle    : 
author      : wangh
job         : study
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Conditions for the CLT

1. Independence: Sampled observations must be independent.
? random sample/assignment
? if sampling without replacement, n < 10% of population
2. Sample size/skew: Either the population distribution is normal, or if the population
distribution is skewed, the sample size is large (rule of thumb: n > 30).

--- .class #id 

## Generate random for the Poisson distribution

generate a sampleSize * n matrix with variables for the Poisson distribution

```{r}
sdf<-matrix(rpois(input$n * as.integer(input$sampleSize), input$lambda), input$n)
```

--- .class #id

## plot
```{r}

      avg<-apply(rand_data(), 1, mean)
      miu<-mean(avg)
      SE_mean<-sd(avg)
      
      wide<-sqrt(input$lambda/10)*3
      g_mean <- ggplot(data.frame(avg), aes(x = avg))
      g_mean <- g_mean + labs(title = paste('mean = ', round(miu,4),", SE = ", round(SE_mean,4)))
      g_mean <- g_mean + labs(x="sample mean")
      g_mean <- g_mean + xlim(miu-wide, miu+wide)
      g_mean <- g_mean + geom_histogram(fill = "salmon",binwidth =wide/40,aes(y = ..density..), colour = "black")
      g_mean <- g_mean + geom_density(size = 1) + geom_vline(xintercept = miu, color="blue",size =1)
      g_mean
```

--- .class #id


